version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: budget_app_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: budget_app
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: budget_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - budget_network

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: budget_app_api
    restart: unless-stopped
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: budget_app
      DB_USER: budget_user
      DB_PASSWORD: budget_password
      PORT: 3001
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - budget_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: budget_app_frontend
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:3001
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - budget_network

volumes:
  postgres_data:
    driver: local

networks:
  budget_network:
    driver: bridge