version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: budget_app_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: budget_app
      POSTGRES_USER: budget_user
      POSTGRES_PASSWORD: budget_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - budget_network

volumes:
  postgres_data_dev:
    driver: local

networks:
  budget_network:
    driver: bridge